# Dockerfile

FROM python:3.10-slim

# Variables d'environnement
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Installer les dépendances système si besoin
RUN apt-get update && apt-get install -y gcc

# Créer le répertoire de l'application
WORKDIR /app

# Copier les fichiers du projet
COPY . .


# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port FastAPI (par défaut uvicorn sur 8000)
EXPOSE 8000

# Lancer uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
